services:

  # Dịch vụ Nginx - Máy chủ web xử lý yêu cầu HTTP
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html # Mount thư mục mã nguồn vào container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Sử dụng file cấu hình Nginx tùy chỉnh
    depends_on: # Chỉ cần chạy server thì có thể chạy luôn php và mysql
      - php
      - mysql

  # Dịch vụ PHP - Chạy ứng dụng Laravel (FPM)
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # Mount mã nguồn với hiệu suất tối ưu

  # Dịch vụ MySQL - Cơ sở dữ liệu
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  # Dịch vụ Composer - Quản lý package PHP
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      # Cho phép Composer cài đặt package trực tiếp vào folder mã nguồn
      - ./src:/var/www/html
      
  # Service PHP Artisan - dùng để chạy các lệnh Artisan trong Laravel
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile # Sử dụng Dockerfile PHP đã định nghĩa
    volumes:
      - ./src:/var/www/html
    # Vì sử dụng dockerfile php, nên phải thiết lập entrypoint aritsan trong file compose
    entrypoint: ["php", "/var/www/html/artisan"]

  # Service NPM - dùng để chạy các lệnh NPM cho frontend
  npm:
    image: node:14
    working_dir: /var/www/html # Thiết lập thư mục làm việc trong container
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]